name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - .github/workflows/firebase-hosting-pull-request.yml
      - .github/workflows/firebase-firestore-merge.yml
      - .github/workflows/firebase-functions-merge.yml
      - .github/workflows/firebase-storage-merge.yml
      - "functions/**"
      - "firestore.*"
      - "storage.*"
jobs:
  build_and_deploy:
    env:
      WORK_DIR: $RUNNER_TEMP/work
      GOOGLE_APPLICATION_CREDENTIALS: $RUNNER_TEMP/work/service-account.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set secret
        run: |
          mkdir $WORK_DIR
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_BREAM }}' \
          > $GOOGLE_APPLICATION_CREDENTIALS
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - run: npm ci --prefix functions
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_BREAM }}
          channelId: live
          projectId: black-bream
