name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
    paths:
      - "firestore.*"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: |
          npm ci
          npm ci --prefix functions
      - name: Deploy Firestore
        env:
          WORK_DIR: $RUNNER_TEMP/work
          GOOGLE_APPLICATION_CREDENTIALS: $RUNNER_TEMP/work/service-account.json
        run: |
          mkdir $WORK_DIR
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_BREAM }}' \
          > $GOOGLE_APPLICATION_CREDENTIALS
          npx firebase deploy --only firestore
