name: Functions on merge deployment
on:
  workflow_call:
    inputs:
      site-id:
        required: true
        type: string
    secrets:
      firebase_service_account:
        required: true
jobs:
  deploy_functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci && npm ci --prefix functions
      - run: npm test
      - run: cp -r .github/sites/${{ inputs.site-id }}/* ./

      - name: Deploy Functions
        env:
          WORK_DIR: ${{ runner.temp }}/${{ inputs.site-id }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/${{ inputs.site-id }}/service-account.json
        run: |
          mkdir $WORK_DIR
          echo '${{ secrets.firebase_service_account }}' \
          > $GOOGLE_APPLICATION_CREDENTIALS
          npx firebase deploy --only functions --force --project ${{ inputs.site-id }}
      - name: Set dataVersion
        env:
          WORK_DIR: ${{ runner.temp }}/${{ inputs.site-id }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/${{ inputs.site-id }}/service-account.json
        run: |
          npx firebase firestore:delete service/dataVersion --force --project ${{ inputs.site-id }}
