name: Functions on merge deployment
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/on-call-functions.yml
      - .github/workflows/on-merge-functions.yml
      - .github/sites/**/*
      - "functions/**/*"
jobs:
  coverage:
    uses: ./.github/workflows/on-call-coverage.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  black-bream:
    needs: [coverage]
    uses: ./.github/workflows/on-call-functions.yml
    with:
      site-id: black-bream
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_BREAM }}
  grey-bream:
    needs: [coverage]
    uses: ./.github/workflows/on-call-functions.yml
    with:
      site-id: grey-bream
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GREY_BREAM }}
  white-bream:
    needs: [coverage]
    uses: ./.github/workflows/on-call-functions.yml
    with:
      site-id: white-bream
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHITE_BREAM }}
