name: Hosting on merge deployment
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - .github/workflows/on-call-hosting.yml
      - .github/workflows/on-merge-hosting.yml
      - .github/sites/**/*
      - public/**/*
      - src/**/*
      - test/unit/**/*
      - "*.config.js"
      - "*theme.js"
      - package*.json
      - index.html
      - .nvmrc
jobs:
  black-bream:
    uses: ./.github/workflows/on-call-hosting.yml
    with:
      site-id: black-bream
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BLACK_BREAM }}
      firebase_api_key: ${{ secrets.FIREBASE_API_KEY_BLACK_BREAM }}
      firebase_recaptcha_key: ${{ secrets.FIREBASE_RECAPTCHA_KEY_BLACK_BREAM }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
  grey-bream:
    uses: ./.github/workflows/on-call-hosting.yml
    with:
      site-id: grey-bream
    secrets:
      firebase_service_account: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GREY_BREAM }}
      firebase_api_key: ${{ secrets.FIREBASE_API_KEY_GREY_BREAM }}
      firebase_recaptcha_key: ${{ secrets.FIREBASE_RECAPTCHA_KEY_GREY_BREAM }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
